version: "3.3"

services:
  ui:
    image: portal/ui
    container_name: portal-ui
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
  nginx:
    image: nginx:1.17.9-alpine
    container_name: ui-nginx
    ports:
      - 8000:8080
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
